////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== core



=== Purpose


The core plugin adds methods and beans that other plugins rely upon


=== Description


This plugin configures Grails to use Spring MVC at its core to deal with web requests. The plugin configures the `GrailsDispatcherServlet` and necessary Spring beans (see below) for controllers, tag libraries and Groovy Server Pages (GSP)

Configured Spring Beans:

* `classLoader` - A bean that refers to the GroovyClassLoader used to load this GrailsApplication
* `classEditor` - A PropertyEditor that populates classes with String data
* `customEditors` - An instance of {springapi}org/springframework/beans/factory/config/CustomEditorConfigurer.html[CustomEditorConfigurer], that uses allows the `classEditor` bean to be used as a `PropertyEditor`
