////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== dataSource



=== Purpose


The `dataSource` plugin configures the Grails JDBC `DataSource`.


=== Examples


A `DataSource` configured with explicit settings in `grails-app/conf/application.groovy`:

[source,groovy]
----
dataSource {
    pooled = true
    dbCreate = "update"
    url = "jdbc:mysql://localhost/yourDB"
    driverClassName = "com.mysql.jdbc.Driver"
    username = "yourUser"
    password = "yourPassword"
}
----

A `DataSource` configured to look up via JNDI:

[source,groovy]
----
dataSource {
    jndiName = "java:comp/env/myDataSource"
}
----


=== Description


Refer to the section on link:{guidePath}/conf.html#dataSource[Data Sources] in the Grails user guide.

Configured Spring Beans:

* `dataSource` - An instance of the Apache DBCP library's `org.apache.commons.dbcp.BasicDataSource` class or a {springapi}org/springframework/jndi/JndiObjectFactoryBean.html[JndiObjectFactoryBean] in the case of a JNDI `DataSource`
