////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== services



=== Purpose


The `services` plugin configures Grails' support for link:{guidePath}/services.html[Services].


=== Examples


An example service class in the `grails-app/services` directory:

[source,groovy]
----
class BookService {
    Book[] getBooks() {
        Book.list() as Book[]
    }
}
----


=== Description


Refer to the section on link:{guidePath}/services.html[Services] in the Grails user guide which details Grails' services.

Configured Spring Beans given a service class of `BookService`:

* `BookServiceServiceClass` - The https://docs.grails.org/{GrailsVersion}/apiorg/codehaus/groovy/grails/commons/GrailsServiceClass.html[GrailsServiceClass] instance which implements the conventions defined within a services class.
* `BookService` - A bean configured according to the scope of the service: if the service is transactional then the type of the actual bean definition will be a {springapi}org/springframework/transaction/interceptor/TransactionProxyFactoryBean.html[TransactionProxyFactoryBean].
