////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== URLMappings



=== Purpose


The `URLMappings` plugin configures Grails' URL Mapping infrastructure.


=== Examples


An example `UrlMapping` class:

[source,groovy]
----
class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
    }
}
----


=== Description

Refer to the section on link:{guidePath}/theWebLayer.html#urlmappings[URL Mappings] in the Grails user guide which details Grails' URL mappings.

Configured Spring Beans:

* `grailsUrlMappingsHolderBean` - A {apiDocs}org/grails/web/mappings/UrlMappingsHolderFactoryBean.html[UrlMappingsHolderFactoryBean] factory bean that constructs a {apiDocs}grails/web/mapping/UrlMappingsHolder.html[grails.web.mapping.UrlMappingsHolder] instance that stores all of the URL mappings.
* `urlMappingsTargetSource` - A Spring {springapi}org/springframework/aop/target/HotSwappableTargetSource.html[HotSwappableTargetSource] used in auto-reloading to automatically update URL mappings when changed.
* `grailsUrlMappingsHolder` - A Spring {springapi}org/springframework/aop/framework/ProxyFactoryBean.html[ProxyFactoryBean] that proxies onto the actual `UrlMappingsHolder` instance using the `HotSwappableTargetSource`
