////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== attributes



=== Purpose


Adds custom attributes to scaffolding tags.


=== Examples


[source,groovy]
----
birthDate attributes: [years: 2000..2011]
----


=== Description


Adds extra attributes to the GSP tag used to display the edit field for the specified domain class property. For example, the rendered tag in scaffolding for the `birthDate` property above would look like:

[source,xml]
----
<g:datePicker name="birthDate" ... years="2000..2011" ... />
----

Hence, the scaffolded view would limit a user to the years 2000-2011, as dictated by the g:datePicker tag.

NOTE: This constraint only works for boolean (checkbox), date (datePicker), and collection (*select) properties.

Error Code: This constraint only impacts the scaffolding and does not create errors.
