////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== email



=== Purpose


Validates that a String value is a valid email address.


=== Examples


[source,groovy]
----
homeEmail email: true
----


=== Description


Set to `true` if a string value must be an email address. 

Internally uses the `org.apache.commons.validator.routines.EmailValidator` class (i.e. in contrast to earlier Grails versions no longer the deprecated `org.apache.commons.validator.EmailValidator` with the most notable difference that the new version validates the emails TLDs).

Error Code: `className.propertyName.email.invalid`
