////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== inList



=== Purpose


Validates that a value is within a range or collection of constrained values.


=== Examples


[source,groovy]
----
name inList: ["Joe", "Fred", "Bob"]
----


=== Description


Constrains a value so that it must be contained within the given list.

This constraint influences  link:{hibernate5Guide}/manual/index.html#constraints[schema generation].

Error Code: `className.propertyName.not.inList`
