////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== max



=== Purpose


Ensures a value does not exceed a maximum value.


=== Examples


[source,groovy]
----
age max: new Date()
price max: 999F
----


=== Description


Sets the maximum value of a class that implements `java.lang.Comparable`. The type of the value must be the same as the property.

Note that constraints are only evaluated once which may be relevant for a constraint that relies on a value like an instance of `java.util.Date`.

[source,groovy]
----
class User {
    ...

    static constraints = {
        // this Date object is created when the constraints are evaluated, not
        // each time an instance of the User class is validated.
        birthDate max: new Date()
    }
}
----

This constraint influences  link:{hibernate5Guide}/manual/index.html#constraints[schema generation].

Error Code: `className.propertyName.max.exceeded`
