////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== range



=== Purpose


Uses a Groovy range to ensure that a property's value is within a specified range


=== Examples


[source,groovy]
----
age range: 18..65
----


=== Description


Set to a Groovy range which can contain numbers in the form of an `IntRange`, dates or any object that implements `Comparable` and provides `next` and `previous` methods for navigation.

This constraint influences  link:{hibernate5Guide}/manual/index.html#constraints[schema generation].

Error Code: `className.propertyName.range.toosmall` or `className.propertyName.range.toobig`
