////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== widget



=== Purpose


Changes the HTML form field type used in scaffolding the associated domain class property.


=== Examples


[source,groovy]
----
description widget: 'textarea'
----


=== Description


Changes the GSP tag used for editing values of the corresponding domain class property in the scaffolding. For example, the above would cause the scaffolding to use `<g:textArea ... />` for 'description' edit fields.

NOTE: This constraint is also added to scaffolding tags for boolean (checkbox), date (datePicker), and collection (*select) properties, but it has no effect in those cases.

Error Code: This constraint only impacts look and does not create errors.
