////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


==== Detecting Versions at Runtime


You can detect the application version using Grails' support for application metadata using the {apiDocs}grails/core/GrailsApplication.html[GrailsApplication] class. For example within link:theWebLayer.html#controllers[controllers] there is an implicit link:../ref/Controllers/grailsApplication.html[grailsApplication] variable that can be used:

[source,groovy]
----
def version = grailsApplication.metadata.getApplicationVersion()
----

You can retrieve the version of Grails that is running with:

[source,groovy]
----
def grailsVersion = grailsApplication.metadata.getGrailsVersion()
----

or the `GrailsUtil` class:

[source,groovy]
----
import grails.util.GrailsUtil
...
def grailsVersion = GrailsUtil.grailsVersion
----
