////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== Multi-Tenancy
GORM for MongoDb supports the following multi-tenancy modes:

* `DATABASE` - A separate database with a separate connection pool is used to store each tenants data.
* `SCHEMA` - The same database, but different schemas are used to store each tenants data.
* `DISCRIMINATOR` - The same database is used with a discriminator used to partition and isolate data.

include::configuration.adoc[]

include::tenantTransforms.adoc[]

include::multiTenancyModes.adoc[]

include::dynamicConnectionSources.adoc[]
