////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

===== Purpose

Returns the name of the MongoDB https://api.mongodb.org/java/current/com/mongodb/DBCollection.html[collection] used for the current domain class

===== Examples

[source,java]
----
println Book.collectionName
----

===== Description

The `collectionName` property allows introspection of the name of the https://api.mongodb.org/java/current/com/mongodb/DBCollection.html[DBCollection] object used by a given domain class. Can be used in conjunction with `useCollection` to switch to different collections and back again.
