////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

===== Purpose

Returns the MongoDB https://api.mongodb.com/java/current/org/bson/Document.html[Document] for an instance of a domain class

WARNING: Using the `Document` object directly is discouraged, because it's inefficient. It's better to use <<dynamicAttributes>>.

===== Examples

[source,groovy]
----
def b = Book.get(1)

println b.dbo
----

===== Description

The `dbo` property allows access to the underlying MongoDB https://api.mongodb.com/java/current/org/bson/Document.html[Document], which is a respresentation of the stored BSON document that can be manipulated in memory.
