////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

GORM Data Services have built in support for `jakarta.validation` annotations for method parameters.

You will need to have a `jakarta.validation` implementation on your classpath (such as `hibernate-validator` and then simply annotate your method parameters using the appropriate annotation. For example:

[source,groovy]
----
import jakarta.validation.constraints.*

@Service(Book)
interface BookService {

    Book find(@NotNull String title)
}
----

In the above example the `NotNull` constraint is applied to the `title` property. If `null` is passed to the method a `ConstraintViolationException` exception will be thrown.