////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
==== 6.0.0-M4

* In the previous release, the grailsVersion and grailsGradlePlugin version points to the 6.0.0-SNAPSHOT for a newly created Grails application. This Release fix the problem by correctly pointing them to 6.0.0-M4.
* There was no embedded servlet selected by default, but this release select Embedded Tomcat as the default servlet implementation.
* Add New Option for selecting the Embedded Servlet implementation between Tomcat, Jetty, Undertow, or None.

==== 6.0.0-M3

* Initial Milestone Release

==== 6.0.0-M2

* Initial Milestone Release