info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
grails:
    codegen:
        defaultPackage: @grails.codegen.defaultPackage@
        profile: @grails.profile@
spring:
    jmx:
        unique-names: true
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback-spring.xml'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false
