////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== Usage

To render markup, inject the link:api/org/grails/scaffolding/markup/DomainMarkupRenderer.html[DomainMarkupRenderer].

[source,groovy,indent=1]
DomainMarkupRenderer domainMarkupRenderer

Then execute one of the methods provided:

* `renderOutput` (Show page)
* `renderInput` (Edit/Create page)
* `renderListOutput` (List page)

A string containing all of the markup will be returned.

Each of the methods requires a link:{gormApiDocs}/org/grails/datastore/mapping/model/PersistentEntity.html[PersistentEntity] that represents the given domain class. To retrieve the link:{gormApiDocs}/org/grails/datastore/mapping/model/PersistentEntity.html[PersistentEntity], inject the mapping context and pass in the fully qualified domain class name.

[source,groovy,indent=1]
----
MappingContext grailsDomainClassMappingContext

grailsDomainClassMappingContext.getPersistentEntity("test.foo.Bar")
----