////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

If you prefer to keep the declaration of the URL mapping in your `UrlMappings.groovy` file then simply removing the `uri` attribute of the `Resource` transformation and adding the following line to `UrlMappings.groovy` will suffice:

[source,groovy]
----
"/books"(resources:"book")
----

Extending your API to include more end points then becomes trivial:

[source,groovy]
----
"/books"(resources:"book") {
    "/publisher"(controller:"publisher", method:"GET")
}
----

The above example will expose the URI `/books/1/publisher`.

A more detailed explanation on link:theWebLayer.html#restfulMappings[creating RESTful URL mappings] can be found in the link:theWebLayer.html#urlmappings[URL Mappings section] of the user guide.
