////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
* Download the latest binary from https://github.com/apache/grails-forge/releases/[Grails Forge Release]
* Extract the binary to appropriate location (For example: `C:\grails`)
* Create an environment variable `GRAILS_HOME` which points to the installation directory i.e. `C:\grails`
* Update the `PATH` environment variable, append `%GRAILS_HOME%\bin`.

You should now be able to run the Grails Forge CLI from the command prompt as follows:

[source,bash]
----
$ grails
| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
grails>
----
