////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

When you use the `create-*` and `generate-*` commands, Grails automatically generates `unit` or `integration` tests. For example, running the link:../ref/Command%20Line/create-controller.html[create-controller] command as follows:

[source,groovy]
----
grails create-controller com.acme.app.simple
----

Grails generates a controller at `grails-app/controllers/com/acme/app/SimpleController.groovy`, and a corresponding unit test at `src/test/groovy/com/acme/app/SimpleControllerSpec.groovy`. It's important to note that Grails only creates the test structure; you need to implement the test logic.

NOTE: The default class name suffix is `Spec` as of Grails 3.x.