////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

In Grails versions earlier than 3.3, Grails used Reactor 2.x which provided `@Consumer` and `@Selector` annotations to listen for events. For example:

[source,groovy]
----
import reactor.spring.context.annotation.*

@Consumer
class MyService {
	@Selector('myEvent')
	void myEventListener(Object data) {
		println "GOT EVENT $data"
	}
}
----

Within the `grails-events-compat` dependency Grails 3.3 and above ship versions of these annotations that bridge and provide compatibility for applications upgrading to Grails 3.3, however these annotations are considered deprecated and the link:{asyncApi}/grails/events/annotation/Subscriber.html[Subscriber] annotation should be used instead which provides equivalent functionality.