////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

If you include one of the aforementioned concrete `EventBus` implementations for RxJava or GPars then it is a matter of configuring the appropriate implementation.

TIP: With RxJava 1.x this is done with link:{rxjavadocs}/rx/plugins/RxJavaHooks.html[RxJavaHooks], with RxJava 2.x with link:{rxjava2docs}/io/reactivex/plugins/RxJavaPlugins.html[RxJavaPlugins] and with GPars with link:{gparsdocs}/groovyx/gpars/GParsConfig.html[GParsConfig]

If you use the default implementation then you can override the thread pool used by the `EventBus` by registering the appropriate bean in `grails-app/conf/spring/resources.groovy`:

.grails-app/conf/spring/resources.groovy
[source,groovy]
----
import org.grails.events.bus.*
import java.util.concurrent.*

beans = {
    eventBus(ExecutorEventBus, Executors.newFixedThreadPool(5))
}
----
