////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Spring also fires a number of useful events. All events in the `org.springframework` use the `spring` namespace. However, these events are disabled by default as they add a performance overhead.

To enable Spring Event translation set `grails.events.spring` to `true` in `application.yml` prior to defining subscribers.

For example:

[source,groovy]
----
import grails.events.annotation.*
import org.springframework.web.context.support.*
import org.springframework.boot.context.event.*
...

@Events(namespace="spring")
class MyService {

    @Subscriber
    void applicationStarted(ApplicationStartedEvent event) {
        // fired when the application starts
    }

    @Subscriber
    void servletRequestHandled(RequestHandledEvent event) {
        // fired each time a request is handled
    }
}
----