////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== defaultAction



=== Purpose


Specifies the default action to be executed if none is specified in the URI.

This is unnecessary if you have an action named "index" and want it to be the default, since that happens automatically.


=== Examples


[source,groovy]
----
class BookController {

    static defaultAction = "list"

    def list() {
        [books: Book.list()]
    }

    def show() {
        [bookInstance: Book.get(params.id)]
    }
}
----
