////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== forward



=== Purpose


Forwards a request from one controller to the next without issuing an HTTP redirect.


=== Examples


[source,groovy]
----
forward action: "show"

forward controller: "book", action: "list"

forward action: "show", id: 4, params: [author: "Stephen King"]

forward controller: "book", action: "show"
----


=== Description


Forwards the current action to another action, optionally passing parameters and/or errors.


=== Parameters


* `controller` - The controller to redirect to; defaults to the current controller if not specified
* `namespace` (optional) - the namespace of the controller to forward to
* `action` - The action to redirect to, either a string name or a reference to an action within the current controller
* `id` - The id to use in redirection
* `params` - Parameters to pass to the action redirected to.
