////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== responseFormats



=== Purpose


Statically defines the supported response formats used by the link:respond.html[respond] method.


=== Examples


[source,groovy]
----
class BookController {
    static responseFormats = ['xml', 'json']

    def show(Long id) {
        respond Book.get(id)
    }
}
----


=== Description


The `responseFormats` property is used to define the response formats supported by a controller and in turn used by the `respond` method. The `respond` method uses link:{guidePath}/theWebLayer.html#contentNegotiation[Content Negotiation] to respond with the most appropriate content type. See the documentation on link:{guidePath}/webServices.html#REST[REST support] for more information.

