////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== scope



=== Purpose


Changes the scope of a controller


=== Examples


[source,groovy]
----
class BookController {

    static scope = "session"

    // ...
}
----


=== Description


Unless specified by the `grails.controllers.defaultScope` property in `application.yml`, controllers by default are "singleton" scoped which means that only one instance of the controller exists.
This behaviour can be set for an individual controller by specifying a `scope` attribute with one of the following values:

* `singleton` (default) - Only one instance of the controller ever exists (recommended for actions as methods)
* `prototype` - A new controller will be created for each request (recommended for actions as Closure properties)
* `session` - One controller is created for the scope of a user session

See link:{guidePath}/theWebLayer.html#controllersAndScopes[Controllers and Scopes] in the user guide for more information.
