////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== console

=== Purpose

Starts an instance of the Swing graphical Groovy console with an initialized Grails runtime.

=== Examples

[source,groovy]
----
grails console
----

=== Description


Starts the Grails console, which is an extended version of the regular Groovy console. There are a couple of useful variables registered in the binding:

* `ctx` - The Spring ApplicationContext instance
* `grailsApplication` - The GrailsApplication instance

These are useful as they allow access to the conventions within Grails and Spring beans.

Usage:
[source,groovy]
----
grails <<environment>>* console
----

