////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== create-profile

=== Purpose

The starting point for creating a Grails profile. This command will create a profile project with an appropriate Gradle build that can be published to your local Maven cache or a Maven repository.

=== Examples

[source,groovy]
----
grails create-profile mycompany
----

=== Description

Usage:
[source,groovy]
----
grails create-profile <<name>>
----
