////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== create-taglib

=== Purpose

The `create-taglib` command creates a tag library and associated unit test for the given base name.

=== Examples

[source,groovy]
----
grails create-taglib
grails create-taglib book
grails create-taglib org.bookstore.Book
----

=== Description

Creates a tag library for the given base name. The argument is optional, but if you don't include it the command will ask you for the name of the tag library.

A link:{guidePath}/theWebLayer.html#taglibs[tag library] is a "view helper" that in MVC terms helps the view with rendering by providing a set of reusable tags.

The name of the tag library can include a Java package, such as `org.bookstore` in the final example above, but if one is not provided a default is used. So the second example will create the file `grails-app/taglibs/<appname>/BookTagLib.groovy` whereas the last one will create `grails-app/taglibs/org/bookstore/BookTagLib.groovy` directory. Note that the first letter of the tag library name is always upper-cased when determining the class name.

If you want the command to default to a different package for tag libraries, provide a value for `grails.project.groupId` in the link:{guidePath}/conf.html[runtime configuration].

Note that this command is just for convenience and you can also create tag libs in your favourite text editor or IDE if you choose.

Usage:
[source,groovy]
----
grails create-taglib <<name>>
----
