////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== install-templates



=== Purpose


Copies the the templates used by Grails during code generation to your project directory


=== Examples


[source,groovy]
----
grails install-templates
----


=== Description


Usage:

[source,groovy]
----
grails install-templates
----

The `install-templates` command will copy the templates Grails uses for all code generation activities to the application's `src/main/templates/scaffolding` directory.


== Gradle runCommand install-templates

=== Purpose

Copies the templates used by Grails during code generation to your project directory

=== Examples

[source,console]
----
$ ./gradlew runCommand -Pargs="install-templates"
----


=== Description

Usage:

[source,console]
----
$ ./gradlew runCommand -Pargs="install-templates"
----

The `install-templates` command will copy the templates Grails uses for all code generation activities to the application's `src/main/templates/scaffolding` directory.
