////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== list-plugins



=== Purpose


Lists the available plugins


=== Examples


[source,groovy]
----
grails list-plugins
----


=== Description


Usage:
[source,groovy]
----
grails list-plugins
grails list-plugins -repository=myRepository
----

Lists the plugins that are installable. Note: This command can take a while to execute depending in your internet connectivity. Typical output looks like this:

[source,groovy]
----
| Available Plugins
* asset-pipeline
* cache
* cache-ehcache
* fields
* geb
* hibernate
* mongodb
* quartz
* scaffolding
----

If you require more info about a plugin you can use the link:plugin-info.html[plugin-info] command.
