////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== list-profiles



=== Purpose


Lists the available profiles


=== Examples


[source,groovy]
----
grails list-profiles
----


=== Description


Usage:
[source,groovy]
----
grails list-profiles
----

Lists the profiles that are available. Note: This command can take a while to execute depending in your internet connectivity. Typical output looks like this:

[source,groovy]
----
| Available Profiles
--------------------
* base - The base profile extended by other profiles
* plugin - Profile for plugins designed to work across all profiles
* profile - A profile for creating new Grails profiles
* web - Profile for Web applications
* rest-api - Profile for Web API applications
* web-plugin - Profile for Plugins designed for Web applications
----

If you require more info about a profile you can use the link:profile-info.html[profile-info] command.
