////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== package-plugin



=== Purpose


Packages a plugin as a JAR archive which can then be installed into another application


=== Examples


[source,groovy]
----
grails package-plugin
----


=== Description


Usage:
[source,groovy]
----
grails package-plugin
----

The plugin archive will be built to the `build/libs` directory by default. You can also install the plugin to your local Maven repository with the `install` command:

[source,groovy]
----
grails install
----
