////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== plugin-info



=== Purpose


Displays detailed info about a plugin


=== Examples


[source,groovy]
----
grails plugin-info shiro
----


=== Description


Usage:
[source,groovy]
----
grails plugin-info <<name>>
----

This command will display more detailed info about a given plugin such as the author, location of documentation and so on. An example of the output of the geb plugin can be seen below:

[source,groovy]
----
| Plugin Info: geb
| Latest Version: 1.0.1-SNAPSHOT
| All Versions: 1.0-SNAPSHOT,1.0.0.M1,1.0.0.M2,1.0.0.M3,1.0.0.M4,1.0.0,1.0.0.BUILD-SNAPSHOT,1.0.1-SNAPSHOT
| Title: Geb Plugin

Plugin that adds Geb functional testing code generation features.

* License: APACHE
* Documentation: https://github.com/apache/grails-core/tree/HEAD/grails-geb#readme
* Issue Tracker: https://github.com/apache/grails-core/issues
* Source: https://github.com/apache/grails-core
----
