////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== shell



=== Purpose


Starts an instance of the Groovy terminal shell with an initialized Grails runtime.


=== Examples


[source,groovy]
----
grails shell
----


=== Description


Usage:
[source,groovy]
----
grails <<environment>>* shell
----

Starts the Grails shell, which is an extended version of the regular Groovy shell. Within the binding of the shell there are a couple of useful variables:

* `ctx` - The Spring ApplicationContext instance
* `grailsApplication` - The GrailsApplication instance

These are useful as they allow access to the conventions within Grails and Spring beans.

Example Shell:

[source,groovy]
----
Groovy Shell (1.8.0, JVM: 1.6.0_26)
Type 'help' or '\h' for help.
-----------------------------------
groovy:000>
----
