////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== checkBox



=== Purpose


Generates a checkbox form field. All the usual HTML elements apply.


=== Examples


[source,xml]
----
<g:checkBox name="myCheckbox" value="${true}" />
----


=== Description


Attributes

* `name` - The name of the checkbox
* `value` (optional) - The value of the checkbox
* `checked` (optional) - Expression if evaluates to `true` sets to checkbox to checked

The `checkBox` tag typically only requires the `name` and `value` attributes and will infer whether the checkbox should be checked from the value. The `checked` attribute can be used to override this behaviour for fine-grained control.


