////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== country



=== Purpose


Renders the default English name for a given ISO3166_3 3-letter country code


=== Examples


[,xml]
----
Country: <g:country code="${user.country}"/>
Supported countries: <g:country code="gbr"/>, <g:country code="deu"/>
----


=== Description


Uses the internal ISO3166_3 country code date that the xref:countrySelect.adoc[countrySelect] tag is based upon, to quickly render the name of a country given the code.

For internationalized versions of the country names, define these in your message bundles and use the `<g:message>` tag instead.

Attributes

* `code` - The 3-letter lowercase ISO3166 country code

