////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== currencySelect



=== Purpose


Generates an HTML select tag with currency symbols (e.g. 'EUR', 'USD', etc.)


=== Examples


[source,xml]
----
<g:currencySelect name="myCurrency" value="${currency}" />
----


=== Description


Attributes

* `from` (optional) - The currency symbols to select from, defaults to the major ones if not specified
* `value` (optional) - The currency value as the currency code. Defaults to the currency for the current {javase}java.base/java/util/Locale.html[Locale] if not specified

