////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== fieldValue



=== Purpose


Inspects a bean which has been the subject of xref:../guide/theWebLayer/controllers/dataBinding.adoc[data binding] and obtains the value of the field. If the bean had `errors` during data binding then the originally submitted value is returned from the bean's `errors` object else the value from the bean's property is returned. The value returned will be HTML-encoded.


=== Examples


[,xml]
----
<g:fieldValue bean="${book}" field="title" />

<!-- or as a method -->
<input type="text" value="${fieldValue(bean: book, field: 'title')}" />
----


=== Description


Attributes

* `bean` (required) - The bean instance to inspect
* `field` (required) - The name of the field to obtain the value of


