////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== fieldError



=== Purpose


Renders an error message for the given bean and field.


=== Examples


[source,xml]
----
<g:fieldError bean="${book}" field="title" />
----


=== Description


Attributes

* `bean` (required) - The bean to check for errors
* `field` (required) - The field of the bean or model reference to check
* `message` (optional) -The object to resolve the message for. Objects must implement {springapi}org/springframework/context/MessageSourceResolvable.html[MessageSourceResolvable] interface.
* `encodeAs` (optional) - The name of a codec to apply, i.e. HTML, JavaScript, URL etc.
* `locale` (optional) -  override locale to use instead of the one detected.

