////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== formatBoolean



=== Purpose


Outputs the given boolean as the specified text label.


=== Examples


[,xml]
----
<g:formatBoolean boolean="${myBoolean}" />
<g:formatBoolean boolean="${myBoolean}" true="True!" false="False!" />
----


=== Description


Outputs the given boolean as the specified text label. If the `true` and `false` options are not given, the boolean is output using the default label.

Attributes:

`boolean` - the boolean to output
`true` (optional) - text label for boolean `true` value. `boolean.true` or `default.boolean.true` key is looked up from the Message Source / ResourceBundle (i18n/*.properties) if this attribute is not given.
`false` (optional) - text label for boolean `false` value. `boolean.false` or `default.boolean.false` key is looked up from the Message Source / ResourceBundle (i18n/*.properties) if this attribute is not given.

