////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== if



=== Purpose


The logical if tag to switch on an expression and/or current environment.


=== Examples


[,xml]
----
<g:if test="${name == 'fred'}">
     Hello ${name}!
</g:if>

<g:if env="development">
     Dev mode - debug: $someDebug
</g:if>

<g:if env="production" test="${cacheEnabled}">
     $cache.getContent('1234')
</g:if>
----


=== Description


Attributes

* `test` - The expression to test
* `env` - An environment name

At least one of the attributes must be supplied. If both are supplied they are combined using AND.
