////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== join

=== Purpose


Uses the Groovy JDK {groovyjdk}java/lang/Iterable.html#join(java.lang.String)[join] method to concatenate the `toString()` representation of each item in this collection with the given separator.


=== Examples


[source,xml]
----
<g:join in="['Grails', 'Groovy', 'Gradle']" delimiter="_"/>
----

That would result in output like this:

----
Grails_Groovy_Gradle
----


=== Description


Attributes

* `in` - The collection to iterate over
* `delimiter` (optional) - The value of the delimiter to use during the join. If no delimiter is specified then ", " (a comma followed by a space) will be used

