////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== layoutBody



=== Purpose


Used in layouts to output the contents of the body tag of the decorated page.


=== Examples


Example decorated page:

[source,html]
----
<html>
   <head>
        <meta name="layout" content="myLayout" />
        <script src="myscript.js"></script>
   </head>
   <body>Page to be decorated</body>
</html>
----

Example decorator layout:

[source,html]
----
<html>
   <head>
        <script src="global.js"></script>
        <g:layoutHead />
   </head>
   <body><g:layoutBody /></body>
</html>
----

Results in:

[source,html]
----
<html>
   <head>
        <script src="global.js"></script>
        <script src="myscript.js"></script>
   </head>
   <body>Page to be decorated</body>
</html>
----


