////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== radio



=== Purpose


Generates a radio button


=== Examples


[,xml]
----
<g:radio name="myGroup" value="1"/>
<g:radio name="myGroup" value="2" checked="true"/>
----

results in:

[source,html]
----
<input type="radio" name="myGroup" value="1" />
<input type="radio" name="myGroup" checked="checked" value="2" />
----


=== Description


Attributes

* `value` (required) - The value of the radio button
* `name` (required) - The name of the radio button
* `checked` (optional) - boolean to indicate that the radio button should be checked


