////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== renderErrors



=== Purpose


Renders errors a specified format (at the moment only an HTML list is implemented)


=== Examples


Render a list for the "book" bean:

[source,xml]
----
<g:renderErrors bean="${book}" as="list" />
----

Render a list for the title field of the "book" bean:

[source,xml]
----
<g:renderErrors bean="${book}" as="list" field="title"/>
----


=== Description


Attributes

* `as` (optional) - What to render it as current options are "list" and "xml". Defaults to "list" if not specified.
* `bean` (optional) - The name of the bean to check for errors
* `model` (optional) - The name of the model Map to check for errors
* `field` (optional) - The field within the bean or model to check for errors for

