////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== submitButton



=== Purpose


Creates a submit button using the indicated value as the caption. JavaScript event handlers can be added using the same parameter names as in HTML.


=== Examples


[source,xml]
----
<g:submitButton name="update" value="Update" />
----


=== Description


Attributes

* `name` (required) - The name of the button
* `value` (required) - The title of the button and name of action when not explicitly defined.

