////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== textField



=== Purpose


Creates an input of type 'text' (a text field). An implicit `id` attribute is given the same value as the name unless you explicitly specify one.


=== Examples


[source,xml]
----
<g:textField name="myField" value="${myValue}" />
----


=== Description


Attributes

* `name` (required) - The name of the text field
* `value` (optional) - The initial text to display in the text field. By default the text field will be empty.


=== Configuration


Some attributes can be defined as Boolean values, but the html specification
mandates the attribute must have the same value as its name. For example,
`disabled`, `readonly` and `checked`. It may be desirable to have additional attributes
(like `required`) behave the same way. This can be controlled with the following config value:

[source,yml]
----
grails:
    tags:
        booleanToAttributes:
            - disabled
            - checked
            - readonly
            - required
----

Defaults are `disabled`, `checked`, `readonly`

