////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== timeZoneSelect



=== Purpose


Helper tag to create HTML select tags for selecting from a list of time zones.


=== Examples


[source,xml]
----
<!-- Create a timezone selector -->
<g:timeZoneSelect name="myTimeZone" value="${tz}" />
----


=== Description


Attributes

* `name` (required) - The name of the select
* `value` (optional) - An instance of {javase}java.base/java/util/TimeZone.html[TimeZone]. Defaults to the time zone for the current {javase}java.base/java/util/Locale.html[Locale] if not specified
* `locale` (optional) - The {javase}java.base/java/util/Locale.html[Locale] to use for formatting the time zone names. Defaults to the current request locale and then system default locale if not specified. A {javase}java.base/java/util/Locale.html[Locale] or parsable locale {javase}java.base/java/lang/String.html[String] value (for example: 'sv_SE').
