////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== uploadForm



=== Purpose


Creates a form that can submit multi-part data for file uploads.


=== Examples


[source,xml]
----
<g:uploadForm name="myUpload">
    <input type="file" name="myFile" />
</g:uploadForm>
----


=== Description


Identical to the standard xref:form.adoc[form] tag except that it sets the `enctype` attribute to `"multipart/form-data"` automatically.

Attributes

* `action` (optional) - the name of the action to use in the link; if not specified the default action will be linked
* `controller` (optional) - the name of the controller to use in the link; if not specified the current controller will be linked
* `id` (optional) - The id to use in the link
* `url` (optional) - A map containing the action, controller, id etc.

