////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

https://gorm.grails.org/{projectVersion}/rx/manual/[RxGORM] is new implementation of GORM that has the following goals:

* Reactive
* Non-blocking
* Stateless
* Simple

RxGORM, unlike the link:async.html#asyncGorm[Asynchronous GORM] implementation, aims to be truly non-blocking, down to the driver level.

The following in an example of RxGORM in action:

[source,groovy]
----
Book.get(id)
    .subscribe { Book it ->
    println "Title = ${it.title}"
}
----

You can combine RxGORM with the https://grails-plugins.github.io/grails-rxjava/latest[RxJava] plugin to implement reactive responses from Grails controllers. For example:

[source,groovy]
----
def show() {
	// returns an rx.Observable
    Book.get(params.id?.toString())
}
----

For more information on how to use RxGORM, see the https://gorm.grails.org/{gormVersion}/rx/manual/[RxGORM user guide].
