////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Multi-Tenancy, as it relates to software developments, is when a single instance of an application is used to service multiple clients (tenants) in a way that each tenants' data is isolated from the other.

This type of architecture is highly common in Software as a Service (SaaS) and Cloud architectures. There are a variety of approaches to multi-tenancy and GORM tries to be flexible in supporting as many as possible.

=== Multi-Tenancy Modes

include::modes.adoc[]

=== Multi-Tenancy Transformations

include::tenantTransforms.adoc[]

=== Database Per Tenant

include::databasePerTenant.adoc[]

=== Schema Per Tenant

include::schemaPerTenant.adoc[]

=== Partitioned Multi-Tenancy

include::discriminatorMultiTenancy.adoc[]

=== Understanding Tenant Resolvers

include::tenantResolvers.adoc[]
