////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

GORM for Neo4j contains some enhancements to the Neo4j Bolt Driver API.


==== Getting Properties from Nodes


The dot operator can be used to obtain properties from a node:

[source,groovy]
----
Node node = ...
def value = node.myProperty

// or

def value = node['myProperty']
----

==== Cast a Node to a Map

Nodes can be cast to maps:


[source,groovy]
----
Node node = ...
Map myMap = node as Map
----
