cache=8.0.0-SNAPSHOT
database-migration=9.0.0-SNAPSHOT
fields=7.0.0-SNAPSHOT
geb=5.0.0-SNAPSHOT
hibernate5=9.0.0-SNAPSHOT
mongodb=9.0.0-SNAPSHOT
views-json-templates=9.0.0-SNAPSHOT
neo4j=8.1.0
scaffolding=7.0.0-SNAPSHOT
views-gradle=7.0.0-SNAPSHOT
views-json=7.0.0-SNAPSHOT
views-markup=7.0.0-SNAPSHOT