cache=8.0.0-SNAPSHOT
database-migration=9.0.0-M3
fields=6.0.0-M3
geb=5.0.0-SNAPSHOT
hibernate5=9.0.0-M3
mongodb=9.0.0-M3
views-json-templates=9.0.0-M3
neo4j=8.1.0
scaffolding=6.0.0-M3
views-gradle=4.0.0-SNAPSHOT
views-json=4.0.0-SNAPSHOT
views-markup=4.0.0-SNAPSHOT