////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

To create an application using the `profile` profile:

[source, bash]
----
grails create-profile myprofile
----

The above statement is equivalent to:

[source, bash]
----
grails create-app myprofile --profile=profile
----

To get information about the profile and available features, when not inside a Grails' project directory:

[source, bash]
----
grails profile-info profile
----

You will see an output similar to:

[source, bash]
----
Profile: profile
--------------------
A profile for creating new Grails profiles

Provided Commands:
--------------------
* install - Installs a profile into the local Maven cache
* help - Prints help information for a specific command
* url-mappings-report - Prints out a report of the project's URL mappings
* open - Opens a file in the project
* gradle - Allows running of Gradle tasks
* clean - Cleans a Grails application's compiled sources
* compile - Compiles a Grails application
* create-command - Creates a new command for the profile
* create-domain-class - Creates a Domain Class
* create-unit-test - Creates a unit test
* assemble - Creates a JAR or WAR archive for production deployment
* test-app - Runs the applications tests
* run-command - Executes Grails commands
* console - Runs the Grails interactive console
* run-script - Executes Groovy scripts in a Grails context
* stop-app - Stops the running Grails application
* stats - Prints statistics about the project
* plugin-info - Prints information about the given plugin
* create-script - Creates a Grails script
* bug-report - Creates a zip file that can be attached to issue reports for the current project
* run-app - Runs a Grails application
* dependency-report - Prints out the Grails application's dependencies
* list-plugins - Lists available plugins from the Plugin Repository
* shell - Runs the Grails interactive shell
* create-creator-command - Creates a new create-* command for the profile
* create-feature - Creates a new profile feature
* create-generator-command - Creates a new generate-* command for the profile
* create-template - Creates a new template for the profile
* create-gradle-command - Creates a new command that invokes Gradle for the profile

Provided Features:
--------------------
* asset-pipeline - Adds Asset Pipeline to a Grails project
* events - Adds support for the Grails EventBus abstraction
* geb2 - Adds Geb dependencies to run functional tests
* gsp - Adds support for GSP to the project
* hibernate5 - Adds GORM for Hibernate 5 to the project
* json-views - Adds support for JSON Views to the project
* less-asset-pipeline - Adds LESS Transpiler Asset Pipeline to a Grails project
* markup-views - Adds support for Markup Views to the project
* mongodb - Adds GORM for MongoDB to the project
* neo4j - Adds GORM for Neo4j to the project
* rx-mongodb - Adds RxGORM for MongoDB to the project
----