////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== attach



=== Purpose


Associates a "detached" domain instance with the current Hibernate session


=== Examples


[source,groovy]
----
def b = Book.get(1)
b.title = "Blah"
b.save(flush:true)

b.discard()

...
if (!b.isAttached()) {
    b.attach()
}
----


=== Description


Hibernate manages persistent instances in a persistence Session. A new Session is created per request and is closed at the end of the request. If an object is retrieved from the Session and placed into a web scope such as the HttpSession it will be "detached" from the Hibernate Session once the Session is closed and discarded. You can use the `attach()` method to re-attach an existing persistent instance to the persistence Session of the current request.
