////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== countBy*



=== Purpose


Dynamic method that uses the properties of the domain class to  query for the count of the number of matching records


=== Examples


Given the domain class `Book`:

[source,groovy]
----
class Book {
    String title
    Date releaseDate
    String author
}
----

The following are all possible:

[source,groovy]
----
def c = Book.countByTitle("The Shining")
c = Book.countByTitleAndAuthor("The Sum of All Fears", "Tom Clancy")
c = Book.countByReleaseDateBetween(firstDate, new Date())
c = Book.countByReleaseDateGreaterThanEquals(firstDate)
c = Book.countByTitleLike("%Hobbit%")
c = Book.countByTitleNotEqual("Harry Potter")
c = Book.countByReleaseDateIsNull()
c = Book.countByReleaseDateIsNotNull()
----


=== Description


GORM supports the notion of  link:{hibernate5Guide}/manual/index.html#finders[Dynamic Finders]. The `countBy*` method counts the number of records for the given expression

The following operator names can be used within the respective dynamic methods:

* `LessThan`
* `LessThanEquals`
* `GreaterThan`
* `GreaterThanEquals`
* `Between`
* `Like`
* `Ilike` (i.e. ignorecase like)
* `IsNotNull`
* `IsNull`
* `Not`
* `Equal`
* `NotEqual`
* `And`
* `Or`

These names can be considered keywords, and you will have problems when querying domain classes that have one of these names as a property name. For more information on  link:{hibernate5Guide}/manual/index.html#finders[dynamic finders] refer to the user guide.
