////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== discard



=== Purpose


Discards any changes that have been made to a persistent instance.


=== Examples


[source,groovy]
----
def b = Book.get(1)
b.title = "Blah"
b.discard() // changes won't be applied now
----


=== Description


The `discard` method informs the persistence context that the instance should not be saved. The `discard` method is equivalent to using Hibernate's https://javadoc.io/doc/org.hibernate/hibernate-core/{hibernate5Version}/org/hibernate/Session.html#evict(java/lang/Object).html[evict] method.

NOTE: Note that this method will not clean or reset the object with the original values; it will just prevent it from being automatically saved by Grails.
