////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== findAllWhere



=== Purpose


Uses named arguments corresponding to property names of the domain class to execute a query returning all matching results.


=== Examples


Given the domain class:

[source,groovy]
----
class Book {

   String title
   Date releaseDate
   String author

   static constraints = {
      releaseDate nullable: true
   }
}
----

You can query in the form:

[source,groovy]
----
def books = Book.findAllWhere(author: "Stephen King", title: "The Stand")

def unreleasedBooks = Book.findAllWhere(releaseDate: null)
----


=== Description


Parameters:

* `queryParams` - A Map of key/value pairs to be used in the query
