////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== findOrSaveWhere



=== Purpose


Uses named arguments corresponding to property names of the domain class to execute a query returning the first matching result. This method behaves just like link:../Domain%20Classes/findWhere.html[findWhere] except that it will never return `null`. If a matching instance cannot be found in the database then a new instance is created, populated with values from the query parameters, saved and returned.  The difference between this method and link:../Domain%20Classes/findOrCreateWhere.html[findOrCreateWhere] is that this method will save a newly created instance where link:../Domain%20Classes/findOrCreateWhere.html[findOrCreateWhere] does not.


=== Examples


Given the domain class:

[source,groovy]
----
class Book {

   String title
   Date releaseDate
   String author

   static constraints = {
      releaseDate nullable: true
   }
}
----

You can query in the form:

[source,groovy]
----
def book = Book.findOrSaveWhere(author: "Stephen King", title: "The Stand")
----


=== Description


Parameters:

* `queryParams` - A Map of key/value pairs to be used in the query. If no matching instance is found then this data is used to initialize a new instance.
