////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== hasMany



=== Purpose


Defines a one-to-many association between two classes.


=== Examples


[source,groovy]
----
class Author {

    String name

    static hasMany = [books: Book]
}
----

In this example we define a one-to-many relationship between the `Author` and `Book` classes (one `Author` has many `Book`s)


=== Description


By default GORM will create a property of type `java.util.Set` using the key inside the definition of the `hasMany` map. For example consider this definition:

[source,groovy]
----
static hasMany = [books: Book]
----

Here a property of type `java.util.Set` called `books` will be created within the defining class. These can then be iterated over and manipulated:

[source,groovy]
----
def a = Author.get(1)
for (book in a.books) { println book.title }
----
