////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== instanceOf



=== Purpose


Determines if a domain class instance is an instance of the specified class, resolving the actual class if the instance is a proxy.


=== Examples


Given the domain classes:

[source,groovy]
----
class Container {
   static hasMany = [children: Child]
}
----

[source,groovy]
----
class Child {
   String name
   static belongsTo = [container: Container]
}
----

[source,groovy]
----
class Thing extends Child {}
----

[source,groovy]
----
class Other extends Child {}
----

Then you can determine the type of the elements in a `Container`'s `children` collection using

[source,groovy]
----
def container = Container.get(id)
for (child in container.children) {
   if (child.instanceOf(Thing)) {
      // process Thing
   }
   else if (child.instanceOf(Other)) {
      // process Other
   }
   else {
      // handle unexpected type
   }
}
----


=== Description


Parameters:

* `clazz` - the type to check
