////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== isAttached



=== Purpose


Returns whether the domain instance is attached to a currently active Hibernate session. This method is often used on conjunction with the link:merge.html[merge] or link:attach.html[attach] methods.


=== Examples


[source,groovy]
----
Book b = session.book
...
if (!b.isAttached()) {
    b.attach()
}
----


=== Description


Persistent instances are associated with a persistence Session. A new Session is created for each request and is closed at the end of the request. If an object is read from the session and placed into a web scope such as the HttpSession it is seen as detached, since the persistence session has been closed. You can use the link:attach.html[attach] method to re-attach an existing persistent instance to the persistence session of the current request.
