////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== last



=== Purpose


Retrieves the last instance of the domain class.


=== Examples


Given the domain class:

[source,groovy]
----
class Person {
    String firstName
    String lastName
    Integer age
}
----

[source,groovy]
----
// retrieve the last person ordered by the identifier
def p = Person.last()

// retrieve the last person ordered by the lastName property
p = Person.last(sort: 'lastName')

// retrieve the last person ordered by the lastName property
p = Person.last('lastName')
----

Parameters:

* `sort` (optional) - The name of the property to sort by

See also:

* link:first.html[first]

NOTE: Note that the first() and last() methods are not supported on domain classes which use a composite primary key.

