////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== mapping



=== Purpose

The `mapping` static property configures how GORM maps the domain class to the database. See the section on the  link:{hibernate5Guide}/manual/index.html#ormdsl[ORM DSL] in the user guide for more information.

=== Examples


[source,groovy]
----
class Person {

    String firstName

    static hasMany = [addresses: Address]

    static mapping = {
        table 'people'
        version false
        id column: 'person_id'
        firstName column: 'First_Name'
        addresses lazy: false
    }
}
----

This example uses the  link:{hibernate5Guide}/manual/index.html#ormdsl[ORM DSL] to map the `Person` class onto a table called `people`
