////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== validate



=== Purpose


Validates a domain class against the applied constraints (see link:{guidePath}/validation.html[validation])


=== Description


The `validate` method validates a domain class based on its defined link:{guidePath}/validation.html#constraints[Constraints]. The errors are stored in the link:errors.html[errors] property of the domain class instance.

The `validate` method accepts an optional `List` argument which contains the names of the properties to be validated. When a `List` of names is specified, only those properties will be validated.


=== Examples


[source,groovy]
----
def b = new Book(title: "The Shining")
if (!b.validate()) {
    b.errors.allErrors.each {
        println it
    }
}
----

[source,groovy]
----
def a = new Album(artist: "Genesis", title: "Nursery Cryme", releaseDate: 1971)

// only validate title and releaseDate
if (!a.validate(["title", "releaseDate"])) {
    a.errors.allErrors.each {
        println it
    }
}
----

Parameters:

* `deepValidate` (optional) - Whether associations of the domain instance should also be validated, i.e. whether validation cascades. This is `true` by default; set it to `false` to disable cascading validation.
