////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== where



=== Purpose


Defines a new `grails.gorm.DetachedCriteria` instance.


=== Examples


Basic query:

[source,groovy]
----
def query = Person.where {
   firstName == "Bart"
}
Person bart = query.find()
----

Conjunctions/Disjunctions:

[source,groovy]
----
def query = Person.where {
    (lastName != "Simpson" && firstName != "Fred") || (firstName == "Bart" && age > 9)
}
def results = query.list(sort:"firstName")
----

Property comparison:

[source,groovy]
----
def query = Person.where {
   firstName == lastName
}
----

Querying Associations:

[source,groovy]
----
def query = Pet.where {
    owner.firstName == "Joe" || owner.firstName == "Fred"
}
----

Subqueries:


[source,groovy]
----
final query = Person.where {
  age > avg(age)
}
----


=== Description


The `where` method is a powerful new type-safe querying option introduced in Grails 2.0. For more information on using the `where` method see the dedicated section on  link:{hibernate5Guide}/manual/index.html#whereQueries[Where Queries] and  link:{hibernate5Guide}/manual/index.html#detachedCriteria[Detached Criteria] in the user guide.
