////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

To create a Grails application you first need to familiarize yourself with the usage of the `grails` command which is used in the following manner:

[source,console]
$ grails <<command name>>

Run link:../ref/Command%20Line/create-app.html[create-app] to create an application:

NOTE: The `create-app` command is supported by both the Grails Shell CLI and the Grails Forge CLI.

Grails Shell CLI
[source,console]
$ grails create-app myapp

Grails Forge CLI
[source,console]
$ grails -t forge create-app myapp

This will create a new directory inside the current one that contains the project. Navigate to this directory in your console:

[source,console]
$ cd myapp