////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Use the `grails.testing.services.ServiceUnitTest` trait to unit
test services.

[source,groovy]
.grails-app/services/demo/HelperService.groovy
----
include::{functionalSourceDir}/demo33/grails-app/services/demo/HelperService.groovy[tags=basic_declaration,indent=0]
----

[source,groovy]
.src/test/groovy/demo/HelperServiceSpec.groovy
----
include::{functionalSourceDir}/demo33/src/test/groovy/demo/HelperServiceSpec.groovy[tags=basic_declaration,indent=0]
----

Adding the `ServiceUnitTest` trait to a test causes a new `service` property to
be automatically created for the Service class under test.