////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

GSP also supports a few JSP-style page directives.

The import directive lets you import classes into the page. However, it is rarely needed due to Groovy's default imports and xref:tags.adoc[GSP Tags]:

[,xml]
----
<%@ page import="java.awt.*" %>
----

Separate imports with semicolons `;`. As a convention, you should split larger number of imports into separate lines to improve readability, which requires adding backslash `\` at the end of each line:

[,xml]
----
<%@ page import="java.awt.*; \
your.custom.ComponentA; \
your.custom.ComponentB;"
%>
----

GSP also supports the contentType directive:

[,xml]
----
<%@ page contentType="application/json" %>
----

The contentType directive allows using GSP to render other formats.
