////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Within the `<% %>` brackets you can declare variables:

[,]
----
<% now = new Date() %>
----

and then access those variables later in the page:

[,]
----
<%=now%>
----

Within the scope of a GSP there are a number of pre-defined variables, including:

* `application` - The {javaee}javax/servlet/ServletContext.html[javax.servlet.ServletContext] instance
* `applicationContext` The Spring {springapi}org/springframework/context/ApplicationContext.html[ApplicationContext] instance
* `flash` - The xref:../../../../ref/Controllers/flash.adoc[flash] object
* `grailsApplication` - The {api}grails/core/GrailsApplication.html[GrailsApplication] instance
* `out` - The response writer for writing to the output stream
* `params` - The xref:../../../../ref/Controllers/params.adoc[params] object for retrieving request parameters
* `request` - The {javaee}javax/servlet/http/HttpServletRequest.html[HttpServletRequest] instance
* `response` - The {javaee}javax/servlet/http/HttpServletResponse.html[HttpServletResponse] instance
* `session` - The {javaee}javax/servlet/http/HttpSession.html[HttpSession] instance
* `webRequest` - The {api}org/grails/web/servlet/mvc/GrailsWebRequest.html[GrailsWebRequest] instance
