////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== flash



=== Purpose


A temporary storage map that stores objects within the session for the next request and the next request only, automatically clearing out the objects held there after the next request completes.


=== Examples


[source,groovy]
----
class BookController {

    def index() {
        flash.message = "Welcome!"
        redirect(action: 'home')
    }

    def home() {}
}
----


=== Description


The flash object is a Map (a hash) which you can use to store key value pairs. These values are transparently stored inside the session and then cleared at the end of the next request.

This pattern lets you use HTTP redirects and retain values that can be retrieved from the flash object.
