////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== pageScope



=== Purpose


A reference to the binding of the GSP that the tag library is being executed within. Allows access to variables set with the xref:../Tags%20-%20GSP/set.adoc[set] tag and those passed to the page from the controller model.


=== Examples


[source,groovy]
----
class BookTagLib {

   def parent = { attrs, body ->
       pageScope.parent = "John"
       out << body()
   }

   def child = { attrs, body ->
       out << "My parent is ${pageScope.parent}"
   }
}
----

[source,xml]
----
<g:parent>
    <g:child /> // Outputs "My parent is John"
</g:parent>
----


=== Description


The `pageScope` variable contains a reference to the underlying model being manipulated by the page. It can also be used to pass variables from parent to child tags.
