////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== params



=== Purpose


A mutable multi-dimensional map (hash) of request (CGI) parameters.


=== Examples


To obtain a request parameter called `id`:
[source,groovy]
----
class ExamplesTagLib {

    def showParameter = {
        out << "Parameter id has the value ${params['id']}"
    }

}
----

[source,xml]
----
<g:showParameter />
----


=== Description


The standard Servlet API provides access to parameters with the `HttpServletRequest` object. Although Grails provides the same capability through the link:{controllersRefFromRef}request.html[request] object, it goes a bit further by providing a mutable map of request parameters called `params`.

The `params` object can be indexed into using the array index operator or de-reference operator, so given the URL `/hello?foo=bar` you can access `foo` with

----
params['id']
----

The params object can also be used to bind request parameters onto the properties of a domain class using either the constructor or the link:{domainClassesRefFromRef}properties.html[properties] property:

