////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== session



=== Purpose


The link:{servletApiRefFromRef}session.html[session] object is an instance of the Servlet API's {jakartaee}jakarta/servlet/http/HttpSession.html[HttpSession] class


=== Examples


[source,groovy]
----
class ExampleTagLib {

    // List all attributes and their values for the current session
    def listSessionAttributes = { Map params ->
        out << params.get("name") << ' : ' << session.getAttribute(params.get("name"))
    }

}
----

[source,xml]
----
<ul>
    <g:each var="elm" in="${session.getAttributeNames()}">
        <li><g:listSessionAttributes name="${elm}" /></li>
    </g:each>
</ul>
----


=== Description


The {jakartaee}jakarta/servlet/http/HttpSession.html[HttpSession] class is useful for associated session data with a client.

NOTE: The additional methods added to the link:{servletApiRefFromRef}session.html[session] object are documented in the Grails Servlet API reference guide
