////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


=== Command Line Usage


Grails incorporates the powerful build system https://gradle.org[Gradle].

The basic usage scenario is:

[source,groovy]
----
grails <<environment>>* <<command name>>
----

Grails searches in the following directories for Gant scripts to execute:

* `USER_HOME/.grails/scripts`
* `PROJECT_HOME/src/main/scripts/`
* `PROJECT_HOME/plugins/*/scripts`
* `GRAILS_HOME/scripts`

If multiple matches are found Grails will give you a choice of which one to execute.

You can specify the environment that the command executes in with an optional environment parameter, either with one of the built-in environment names:

[source,groovy]
----
grails dev run-app
grails test run-app
grails prod run-app
----

Or using a -D argument if the name is not one of the three standard names:

[source,groovy]
----
grails -Dgrails.env=uat run-app
----

Refer to the user guide section on link:{guidePath}/commandLine.html[The Command Line] for more information.


=== Grails Forge Command Line Usage


Grails incorporates a CLI and also uses the powerful build system https://gradle.org[Gradle].

The basic usage scenario is:

[source,console]
----
grails <<command name>> <<options>>*
----

When running Gradle tasks you can specify the environment that the command executes in with an optional grails.env parameter, either with one of the built-in environment names:

[source,console]
----
./gradlew bootRun -Dgrails.env=dev
./gradlew bootRun -Dgrails.env=test
./gradlew bootRun -Dgrails.env=prod
./gradlew bootRun -Dgrails.env=custom
----

Refer to the user guide section on link:{guidePath}/commandLine.html[The Command Line] for more information.
