////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


=== Controller Usage


A controller fulfills the C in the Model View Controller (MVC) pattern and is responsible for handling web requests. In Grails a controller is a class with a name that ends in the convention "Controller" and lives in the `grails-app/controllers` directory. A controller can be created with the link:../Command%20Line/create-controller.html[create-controller] command:

[source,groovy]
----
grails create-controller org.bookstore.hello
----

or with your favourite IDE or text editor.

[source,groovy]
----
package org.bookstore

class HelloController {

    def world() {
        render "Hello World!"
    }
}
----

Each action in the controller is a method or a Closure and it has access to a number of implicit variables and methods.

Refer to the user guide topic on link:{guidePath}/theWebLayer.html#controllers[Controllers] for more information.
