////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


=== Database Mapping Usage


Domain classes in Grails by default dictate the way they are mapped to the database using sensible defaults. You can customize these with the ORM Mapping DSL. For example create a `Book` domain:

[source,groovy]
----
grails create-domain-class org.bookstore.Book
----

And then you can use the `mapping` block to customize the ORM mapping behavior.

[source,groovy]
----
package org.bookstore

class Book {
    String title
    Date releaseDate
    Author author

    static mapping = {
        table "books"
        author column: "auth_id"
    }
}
----

Refer to the user guide section on  link:{hibernate5Guide}/manual/index.html#ormdsl[ORM Mapping] for more information.


=== Global Database Mapping


You can configure mappings globally in `grails-app/conf/runtime.groovy` as follows:

[source,groovy]
----
grails.gorm.default.mapping = {
    cache true
    id generator: 'sequence'
    'user-type'(type: org.hibernate.type.YesNoType, class: Boolean)
}
----
