////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


=== plugin Usage


A plugin provides additional capability to the Grails runtime and is created with the link:../Command%20Line/create-plugin.html[create-plugin] command:

[source,groovy]
----
grails create-plugin simple
----

This will create a plugin project which can then be packaged with link:../Command%20Line/package-plugin.html[package-plugin]:

[source,groovy]
----
grails package-plugin
----

To install the plugin to your local Maven repository you can use the `install` command:

[source,groovy]
----
grails install
----

Refer to the user guide topic on link:{guidePath}/plugins.html[plugins] for more information.



=== Grails Forge Plugin Usage

A plugin provides additional capability to the Grails runtime and is created with the link:../Command%20Line/create-plugin.html[create-plugin] command:

[source,console]
----
grails create-plugin myplugin
----

This will create a plugin project which can then be packaged as a JAR file (build/libs/myplugin-0.1.jar) using the `jar` gradle task:

[source,console]
----
./gradlew jar
----

Refer to the user guide topic on link:{guidePath}/plugins.html[plugins] for more information.
