////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


=== Service Usage


A service contains business logic that can be reused across a Grails application. In Grails a service is a class with a name that ends in the convention "Service" and lives in the `grails-app/services` directory. A service can be created with the link:../Command%20Line/create-service.html[create-service] command:

[source,groovy]
----
grails create-service org.bookstore.Book
----

or with your favourite IDE or text editor.

[source,groovy]
----
package org.bookstore

class BookService {
    Book[] getBooks() {
        Book.list() as Book[]
    }
}
----

Refer to the user guide topic on link:{guidePath}/services.html[Services] for more information.
