////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== cache



=== Purpose


Enables the Hibernate second-level cache for the domain class.


=== Examples


[source,groovy]
----
class Book {
    ...
    static mapping = {
        cache true
    }
}
----


=== Description


Usage: `cache(boolean/string/map)`

Arguments:

* `usage` - The cache usage. Can be `read-only`, `read-write`, `nonstrict-read-write` or `transactional`
* `include` (optional) - Whether to include non-lazy associations. Can be `all` or `non-lazy`

You enable caching per domain class, for example:

[source,groovy]
----
static mapping = {
    cache true
}
----

This will configure the domain class to use a 'read-write' cache, but you can configure whatever cache policy is appropriate (and supported by the cache implementation):

[source,groovy]
----
static mapping = {
    cache 'transactional'
}
----

or

[source,groovy]
----
static mapping = {
    cache usage: 'read-only', include: 'non-lazy'
}
----

You can also configure the cache policy on a per-association basis:

[source,groovy]
----
class Author {

    static hasMany = [books: Book]

    static mapping = {
        books cache: true // or 'read-write' etc.
    }
}
----

For more information see the section on  link:{hibernate5Guide}/manual/index.html#caching[Caching] in the user guide.
