////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== dynamicUpdate



=== Purpose


Whether to dynamically build `UPDATE` queries


=== Examples


[source,groovy]
----
class Book {

    ...

    static mapping = {
        dynamicUpdate true
    }
}
----


=== Description


Usage: `dynamicUpdate(boolean)`

By default Hibernate generates all queries at startup and caches them. This helps performance since insert, update, and delete queries don't have to be dynamically generated at runtime. However, there are certain circumstances where dynamic queries are useful.

For example if you were using custom `UserType` to hash passwords, every time an UPDATE occurred, the password would get re-hashed. The `dynamicUpdate` method lets you turn off the dynamic creation of queries that uses only the properties that are needed to perform the update.
