////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== lazy



=== Purpose


Configures whether to use proxies and lazy loading for one-to-one and many-to-one associations.


=== Examples


[source,groovy]
----
class Book {

    static belongsTo = [author: Author]

    static mapping = {
        author lazy: false
    }
}
----


=== Description


Usage: `association_name(lazy: boolean)`

By default GORM single-ended associations are lazy in that when you load a domain instance, an associated domain is not loaded until accessed. Hibernate creates a dynamic proxy by subclassing the domain class and proxying all methods and property access.

This can have some strange side effects (see https://www.hibernate.org/280.html[this page] on proxies at the Hibernate site) particularly in relation to inheritance. You can tell Hibernate not use proxies for single-ended associations by using the `lazy` argument:

[source,groovy]
----
static mapping = {
    author lazy: false
}
----

See the section on  link:{hibernate5Guide}/manual/index.html#fetching[Eager vs Lazing Fetching] in the user guide.
