////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== sort



=== Purpose


Customizes the default property to sort by for query results.


=== Examples


[source,groovy]
----
class Book {
    ...
    static mapping = {
        sort "releaseDate"
    }
}
----


=== Description


Usage: `sort(string/map)`

By default results are sorted by creation date, and you can specify the column to order by in a query:

[source,groovy]
----
def results = Book.list(sort:"title")
----

However, you can also configure the default sort property:

[source,groovy]
----
static mapping = {
    sort "title"
}
----

in which case the `sort` argument is no longer needed. You can also control the sort order:

[source,groovy]
----
static mapping = {
    sort title: "desc" // or "asc"
}
----
