////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== table



=== Purpose


Customizes the name of the database table associated with the domain class


=== Examples


[source,groovy]
----
class Book {
    static mapping = {
        table "book_catalog"
    }
}
----


=== Description


Usage: `table(string/map)`

Arguments:

* `name` - The table name
* `schema` (optional) - The table schema
* `catalog` (optional) - The table catalog

By default the table that Grails maps a domain class is based on the class name. Grails will take a class name and convert Java style camel-case names into table names with underscores. So for example `ProductReview` becomes `product_review`. You can override this with the `table` method:

[source,groovy]
----
static mapping = {
    table "book_catalog"
}
----

You can also specify a schema and catalog:

[source,groovy]
----
static mapping = {
    table name: "book_catalog", schema: "dbo", catalog: "CRM"
}
----
