////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== updateable



=== Purpose


Determines whether a property's database column is updated when persistent instances are updated.


=== Examples


[source,groovy]
----
class Book {

    String title

    static belongsTo = [author: Author]

    static mapping = {
        author insertable: false
        author updateable: false
    }
}
----


=== Description


Usage: `association_name(updateable: boolean)`

Useful in general where you don't want to update a value (or include the column in the generated SQL) during a `save()`.

In particular this is useful for one-to-many relationships. For example when you store the foreign key in the 'child' table, it's often efficient to save the child using only the foreign key of the parent. You do this by setting the parent object (and the parent foreign key) in the 'child' entity. Setting the attributes insertable:false and updateable:false for the 'belongsTo' parent object lets you insert and update using only the foreign key.

[source,groovy]
----
static mapping = {
    author updateable: false
}
----
