////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== version



=== Purpose


Used to disable optimistic locking or change the column that holds the version.


=== Examples


[source,groovy]
----
class Book {
    ...
    static mapping = {
        version false
    }
}
----


=== Description


Usage: `version(string/boolean)`

By default GORM is configured with  link:{hibernate5Guide}/manual/index.html#locking[optimistic locking] enabled. You can disable this by calling the `version` method with an argument of `false`:

[source,groovy]
----
static mapping = {
    version false
}
----

You can pass the name to the `version` method to change the name of the database column:

[source,groovy]
----
static mapping = {
    version 'revision_number'
}
----
