////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

===== dbm-list-tags

====== Purpose

Lists the tags in the current database.

====== Description

Usage:
[source,java]
----
grails <<environment>> dbm-list-tags --defaultSchema=<<defaultSchema>>
----

Required arguments:

Required arguments: __none__.

Optional arguments:

* `defaultSchema` - The default schema name to use

NOTE: Note that the `defaultSchema` parameter name and value must be quoted if executed in Windows, e.g.
[source,groovy]
----
grails dbm-tag "--defaultSchema=<<defaultSchema>>"
----
