////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

===== dbm-changelog-to-groovy

====== Purpose

Converts a Liquibase XML changelog file to a Groovy DSL file.

====== Description

If the Groovy file name isn't specified the name and location will be the same as the original XML file with a .groovy extension.

Usage:
[source,java]
----
grails <<environment>> dbm-changelog-to-groovy [xml_file_name] [groovy_file_name]
----

Required arguments:

* `xml_file_name` - The name and path of the XML file to convert

Optional arguments:

* `groovy_file_name` - The name and path of the Groovy file
