////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== response



=== Purpose


The `response` object is an instance of the Servlet API's {jakartaee}jakarta/servlet/http/HttpServletResponse.html[HttpServletResponse] class


=== Examples


[source,groovy]
----
class BookController {
    def downloadFile() {
        byte[] bytes = // read bytes
        response.outputStream << bytes
    }
}
----


=== Description


The Servlet API's `HttpServletResponse` class can be used within Grails to perform all typical activities such as writing out binary data, writing directly to the response and sending error response codes to name but a few. Refer to the documentation on the {jakartaee}jakarta/servlet/http/HttpServletResponse.html[HttpServletResponse] class in the Servlet API for more information. Grails provides the following additional methods and/or properties on the `response` object

* `format` - The request format, used for link:{guidePath}/theWebLayer.html#contentNegotiation[Content Negotiation].
* `withFormat(Closure)` - The withFormat method, used for link:{guidePath}/theWebLayer.html#contentNegotiation[Content Negotiation].

Grails also overrides the left shift operator on the `response` object making it easier to write to the response writer:

[source,groovy]
----
response << "Hello World"
----
