////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Typically your model may involve one or many domain instances. JSON views provide a render method for rendering these.

For example given the following domain class:

[source,groovy]
----
class Book {
    String title
}
----

And the following template:

[source,groovy]
----
model {
    Book book
}

json g.render(book)
----

The resulting output is:

[source,groovy]
----
{id:1, title:"The Stand"}
----

You can customize the rendering by including or excluding properties:

[source,groovy]
----
json g.render(book, [includes:['title']])
----

Or by providing a closure to add additional JSON output:

[source,groovy]
----
json g.render(book) {
    pages 1000
}
----