If you are using the REST application or REST or AngularJS profiles, then the JSON views plugin will already be included and you can skip the remainder of this section. Otherwise you will need to modify your `build.gradle` to include the necessary plugin to activate JSON views:

[source,groovy]
----
implementation 'org.apache.grails:grails-views-gson:7.0.0' // or whatever is the latest version
----

TIP: The https://github.com/apache/grails-views[source code repository for JSON views] can be found on Github if you are looking for more documentation and contributions

In order to compile JSON views for production deployment you should also activate the Gradle plugin by first modifying the `buildscript` block:

[source,groovy]
----
buildscript {
    ...
    dependencies {
        ...
        classpath platform("org.apache.grails:grails-gradle-bom:{version}")
        classpath "org.apache.grails:grails-gradle-plugins"
    }
}
----

Then apply the `org.apache.grails.views-json` Gradle plugin after any Grails core gradle plugins:

[source,groovy]
----
...
apply plugin: "org.grails.grails-web"
apply plugin: "org.apache.grails.views-json"
----

This will add a `compileGsonViews` task to Gradle, which is invoked prior to creating the production JAR or WAR file.
