////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

To activate Markup views, add the following dependency to the `dependencies` block of your `build.gradle`:

[source,groovy,subs="attributes"]
compile "org.apache.grails:grails-views-markup"


To enable Gradle compilation of Markup views for production environment add the following to the `buildscript` `dependencies` block:

[source,groovy,subs="attributes"]
buildscript {
    ...
    dependencies {
        ...
        classpath platform('org.apache.grails:grails-gradle-bom:{version}')
        classpath 'org.apache.grails:grails-gradle-plugins'
    }
}

Then apply the `org.apache.grails.gradle.grails-markup` Gradle plugin after any Grails core gradle plugins:

[source,groovy]
...
apply plugin: "org.apache.grails.gradle.grails-web"
apply plugin: "org.apache.grails.gradle.grails-markup"

This will add a `compileMarkupViews` task to Gradle that is executed when producing a JAR or WAR file.
