////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Markup views configuration can be altered with `grails-app/conf/application.yml`. Any of the properties within the link:{api}/grails/plugin/markup/view/MarkupViewConfiguration.html[MarkupViewConfiguration] class and Groovy's http://docs.groovy-lang.org/latest/html/api/groovy/text/markup/TemplateConfiguration.html[TemplateConfiguration] class can be set.

For example:

[source,yaml]
grails:
    views:
        markup:
            compileStatic: true
            cacheTemplates: true
            autoIndent: true
            ...

Alternatively you can register a new `MarkupViewConfiguration` bean using the bean name `markupViewConfiguration` in `grails-app/conf/spring/resources.groovy`.
