////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////


== scope



=== Purpose


Changes the scope of a service


=== Examples


[source,groovy]
----
class BookService {
    static scope = "session"
    ...
}
----


=== Description


By default services are "singleton" scoped which means that clients of a service only ever use a single instance (a singleton) of the service. This behaviour can be changed by specifying a `scope` attribute with on the following values:

* `prototype` - A new service is created every time it is injected into another class
* `request` - A new service will be created per request
* `flash` - A new service will be created for the current and next request only
* `flow` - In web flows the service will exist for the scope of the flow
* `conversation` - In web flows the service will exist for the scope of the conversation. ie a root flow and its sub flows
* `session` - A service is created for the scope of a user session
* `singleton` (default) - Only one instance of the service ever exists

See <<scopedServices,Scoped Services>> in the user guide for more information.
