////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

To see some of these concepts in action and help you get going, the https://docs.grails.org/{GrailsVersion}/guide/single.html#scaffolding[Scaffolding plugin], version 2.0 and above, can generate a REST ready controller for you, simply run the command:


[source,bash]
----
$ grails generate-controller <<Domain Class Name>>
----
