////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

To define which properties of your domain class should be indexed for querying you can do so in the mapping:

[source,groovy]
----
class Club {
    String name

    ...
    static mapping = {
        name index:true
    }
}
----

On startup GORM will use Cypher to create indexes as follows:

[source,groovy]
----
CREATE INDEX ON :Club(name)
----

To define a unique index use `unique` instead:

[source,groovy]
----
class Club {
    String name

    ...
    static mapping = {
        name unique:true
    }
}
----
