////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Since 6.1, GORM for Neo4j features support for Neo4j path queries. To use path queries you must implement the `grails.neo4j.Node` trait in your domain class. For example given the following class:

[source,groovy]
----
include::{testsdir}/grails/gorm/tests/path/domain/Person.groovy[tags=class,indent=0]
----

And the following setup data:

[source,groovy]
----
include::{testsdir}/grails/gorm/tests/path/PathSpec.groovy[tags=model,indent=0]
----

Which creates a friend graph it is possible to find out the shortest path from one friend to another with the `findShortestPath` method which returns a `grails.neo4j.Path` instance:


[source,groovy]
----
include::{testsdir}/grails/gorm/tests/path/PathSpec.groovy[tags=shortestPath,indent=0]
----

You can also find the shortest path without first loading the entities using proxies:

[source,groovy]
----
include::{testsdir}/grails/gorm/tests/path/PathSpec.groovy[tags=shortestPathProxy,indent=0]
----

Finally it is also possible to use Cypher queries to find a path:

[source,groovy]
----
include::{testsdir}/grails/gorm/tests/path/PathSpec.groovy[tags=pathCypher,indent=0]
----