////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

==== f:displayWidget

===== Purpose

`f:displayWidget` renders an appropriate widget for a display property, for example an `<span>${value}</span>` element for a `String` property.

NOTE: Using `f:displayWidget` directly will only be necessary for very specialized cases, usually it will be invoked via `f:display`.


===== Attributes

`f:displayWidget` accepts exactly the same attributes as the link:display.html[f:display] tag (except for `wrapper` and `templates` attributes).

===== Example of a `_displayWidget.gsp`

If you have a domain class with a `java.time.LocalDate` you might want to format it specially:

.grails-app/views/_fields/localDate/_displayWidget.gsp
----
<%@ page import="java.time.format.DateTimeFormatter" %>
<g:set var="localDatePattern" value="${message(code: 'default.localDate.format',default: 'yyyy-MM-dd')}"/>
${value?.format(DateTimeFormatter.ofPattern(localDatePattern, request.getLocale()))}
----