////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

Like https://www.oracle.com/java/technologies/jspt.html[Java Server Pages] (JSP), GSP supports the concept of custom tag libraries. Unlike JSP, Grails' tag library mechanism is simple, elegant and completely reloadable at runtime.

Quite simply, to create a tag library create a Groovy class that ends with the convention `TagLib` and place it within the `grails-app/taglib` directory:

[source,groovy]
----
class SimpleTagLib {

}
----

Now create tags using methods. You can access tag attributes through the implicit `attrs` map and body through the implicit `body` closure:

[source,groovy]
----
class SimpleTagLib {
    def simple() {
        // ...

    }
}
----

Closure field-style tags are still supported for backward compatibility, but method-based tags are the recommended syntax.

The implicit `attrs` property is a `Map` of the tag attributes, while `body()` returns the tag body content when invoked:

[source,groovy]
----
class SimpleTagLib {
    def emoticon() {
       out << body() << (attrs.happy == 'true' ? " :-)" : " :-(")
    }
}
----

For method-based tags, named attributes can also bind directly to method signature arguments:

[source,groovy]
----
class SimpleTagLib {
    def greeting(String name) {
        out << "Hello, ${name}!"
    }
}
----

Used as:

[source,xml]
----
<g:greeting name="Graeme" />
----

As demonstrated above there is an implicit `out` variable that refers to the output `Writer` which you can use to append content to the response. Then you can reference the tag inside your GSP; no imports are necessary:

[source,xml]
----
<g:emoticon happy="true">Hi John</g:emoticon>
----

NOTE: To help IDEs like Spring Tool Suite (STS) and others autocomplete tag attributes, add Javadoc comments with `@attr` descriptions to your tag methods. Since taglibs use Groovy code it can be difficult to reliably detect all usable attributes.

For example:

[source,groovy]
----
class SimpleTagLib {

    /**
     * Renders the body with an emoticon.
     *
     * @attr happy whether to show a happy emoticon ('true') or
     * a sad emoticon ('false')
     */
    def emoticon() {
       out << body() << (attrs.happy == 'true' ? " :-)" : " :-(")
    }
}
----

and any mandatory attributes should include the REQUIRED keyword, e.g.

[source,groovy]
----
class SimpleTagLib {

    /**
     * Creates a new password field.
     *
     * @attr name REQUIRED the field name
     * @attr value the field value
     */
    def passwordField() {
        attrs.type = "password"
        attrs.tagName = "passwordField"
        fieldImpl(out, attrs)
    }
}
----
