////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

GSP also supports logical and iterative tags out of the box. For logic there are xref:../../../../ref/Tags%20-%20GSP/if.adoc[if], xref:../../../../ref/Tags%20-%20GSP/else.adoc[else] and xref:../../../../ref/Tags%20-%20GSP/elseif.adoc[elseif] tags for use with branching:

[,xml]
----
<g:if test="${session.role == 'admin'}">
   <%-- show administrative functions --%>
</g:if>
<g:else>
   <%-- show basic functions --%>
</g:else>
----

Use xref:../../../../ref/Tags%20-%20GSP/each.adoc[each] and xref:../../../../ref/Tags%20-%20GSP/while.adoc[while] tags for iteration:

[,xml]
----
<g:each in="${[1,2,3]}" var="num">
   <p>Number ${num}</p>
</g:each>

<g:set var="num" value="${1}" />
<g:while test="${num < 5 }">
    <p>Number ${num++}</p>
</g:while>
----
