////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== Switching Database or Collection at Runtime
In addition to storing dynamic attributes, as of version 1.3.0 of the plugin you can also switch which database and/or collection to persist to at runtime.

For example:

[source,groovy]
----
Person.withDatabase("administrators") {
    new Person(name:"Bob").save()
}
----

The above example will save a `Person` instance to the 'administrators' database. The database is used for the scope of the closure. You can switch database for the scope of the active session:

[source,groovy]
----
Person.useDatabase("administrators") 
new Person(name:"Bob").save()
----

In addition, there are equivalent `withCollection` and `useCollection` methods for switching collection at runtime.
