name: "Java CI"
on:
  push:
    branches:
      - '[4-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[4-9]+.[0-9]+.x'
  workflow_dispatch:
env:
  GIT_USER_NAME: grails-build
  GIT_USER_EMAIL: grails-build@users.noreply.github.com
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: "📅 Set current date as env variable"
        run: echo "NOW=$(date +'%Y-%m-%dT%H%M%S')" >> $GITHUB_ENV
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔀 Extract branch name"
        id: extract_branch
        run: echo "value=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: "🔨 Build Snapshot Documentation"
        env:
          TARGET_GRAILS_VERSION: ${{ github.event.inputs.grails_version }}
        run: ./gradlew build -PgithubBranch=${{ steps.extract_branch.outputs.value }}
      - name: "📤 Upload Docs Artifacts"
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: grails-docs-${{ env.NOW }}.zip
          path: ./build/distributions/*.zip
      - name: "📤 Publish Snapshot Documentation to Github Pages"
        if: success() && github.event_name == 'push'
        uses: grails/github-pages-deploy-action@f1bddf4d126e4375529c0f397b028eb5ac9a13e6 # 2024-12-22
        env:
          BRANCH: gh-pages
          COMMIT_EMAIL: ${{ env.GIT_USER_EMAIL }}
          COMMIT_NAME: ${{ env.GIT_USER_NAME }}
          FOLDER: build/docs
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SKIP_SNAPSHOT: ${{
              startsWith(steps.extract_branch.outputs.value, '3.3') ||
              startsWith(steps.extract_branch.outputs.value, '4.1') ||
              startsWith(steps.extract_branch.outputs.value, '5.3') || 
              startsWith(steps.extract_branch.outputs.value, '6.2')
            }}
