name: "Java CI"
on:
  push:
    branches:
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  pull_request:
    branches:
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  workflow_dispatch:
jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      found_skip_publish: ${{ steps.check_prevent_property.outputs.value }}
    permissions:
      contents: read
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "🔍 Check if we should skip publish"
        id: check_prevent_property
        run: |
          if grep -q '^preventSnapshotPublish=true' gradle.properties; then
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi
  build:
    name: 'Build'
    needs: skip_check
    permissions:
      contents: read  #  to fetch code (actions/checkout)
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21, 23]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Build project"
        id: build
        run: ./gradlew build assemble groovydoc -PskipFunctionalTests --continue
  functional:
    name: "Functional Tests"
    needs: skip_check
    permissions:
      contents: read  #  to fetch code (actions/checkout)
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '21', '23' ]
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Functional Tests"
        run: ./gradlew build -PonlyFunctionalTests
  publish:
    if: github.event_name == 'push' && needs.skip_check.outputs.found_skip_publish != 'true'
    needs: [build, functional]
    permissions:
      contents: read # limit to read access
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "📤 Publish Snapshot Artifacts to Artifactory (repo.grails.org/libs-snapshot-local)"
        id: publish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: >
          ./gradlew
          -Dorg.gradle.internal.publish.checksums.insecure=true
          publish
  docs:
    if: github.event_name == 'push' && needs.skip_check.outputs.found_skip_publish != 'true'
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read # limit to read access
    steps:
      - name: "📝 Store the target branch"
        id: extract_branch
        run: |
          echo "Determining Target Branch"
          TARGET_BRANCH=${GITHUB_REF#refs/heads/}
          echo $TARGET_BRANCH
          echo "value=${TARGET_BRANCH}" >> $GITHUB_OUTPUT
      - name: "📡 Invoke the grails-doc release workflow"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            try {
              const result = await github.rest.actions.createWorkflowDispatch({
                owner: 'apache',
                repo: 'grails-doc',
                workflow_id: 'gradle.yml',
                ref: '${{ steps.extract_branch.outputs.value }}'
              });
              console.log(result);
            } catch(error) {
              console.error(error);
              core.setFailed(error);
            }
