# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Release - Create grails-forge"
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  #  to create release and upload wrapper
      issues: write  #  to modify milestones
    outputs:
      release_version: ${{ steps.release_version.outputs.value }}
    env:
      GIT_USER_NAME: 'grails-build'
      GIT_USER_EMAIL: 'grails-build@users.noreply.github.com'
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: '🔐 Set up GPG'
        run: |
          echo "${{ secrets.GRAILS_GPG_KEY }}" | gpg --batch --import
          gpg --list-keys
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: '⚙️ Run pre-release'
        uses: apache/grails-github-actions/pre-release@asf
        env:
          RELEASE_SCRIPT_PATH: '.github/scripts/setReleasedGrailsVersion.sh'
      - name: "📝 Store the current release version"
        id: release_version
        run: echo "value=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: "🧩 Assemble"
        run: ./gradlew assemble
      - name: "📦 Generate docs"
        run: ./gradlew docs
      - name: "📤 Upload CLI Zip"
        uses: softprops/action-gh-release@v2
        with:
          files: grails-cli/build/distributions/apache-grails-${{ steps.release_version.outputs.value }}-incubating-bin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Staging Repository"
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-forge:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        run: >
          ./gradlew initializeSonatypeStagingRepository
      - name: "📤 Publish grails-forge"
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-forge:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        run: >
          ./gradlew
          -x initializeSonatypeStagingRepository
          findSonatypeStagingRepository 
          publishToSonatype
      - name: "📤 Close Staging Repository"
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-forge:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        run: >
          ./gradlew
          -x initializeSonatypeStagingRepository
          findSonatypeStagingRepository 
          closeSonatypeStagingRepository
  release:
    environment: release
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for gradle.properties revert
      issues: write # required for milestone closing
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          ref: v${{ needs.publish.outputs.release_version }}
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "⚙️ Run post-release"
        uses: apache/grails-github-actions/post-release@asf
        env:
          RELEASE_SCRIPT_PATH: '.github/scripts/setSnapshotGrailsVersion.sh'
  sdkman:
    environment: sdkman
    name: "Release to SDKMAN!"
    runs-on: ubuntu-24.04
    needs: [publish, release]
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.publish.outputs.release_version }}
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🚀 Grails SDK Minor Release"
        if: contains(needs.build.outputs.release_version, 'M')
        run: ./gradlew sdkMinorRelease
        env:
          GVM_SDKVENDOR_KEY: ${{ secrets.GVM_SDKVENDOR_KEY }}
          GVM_SDKVENDOR_TOKEN: ${{ secrets.GVM_SDKVENDOR_TOKEN }}
      - name: "🚀 Grails SDK Major Release"
        if: startsWith(needs.build.outputs.release_version, '7.') && !contains(needs.build.outputs.release_version, 'M')
        run: ./gradlew sdkMajorRelease
        env:
          GVM_SDKVENDOR_KEY: ${{ secrets.GVM_SDKVENDOR_KEY }}
          GVM_SDKVENDOR_TOKEN: ${{ secrets.GVM_SDKVENDOR_TOKEN }}
