name: "Release"
on:
  workflow_dispatch:
    inputs:
      grails_version:
        description: 'Grails Version (eg: 4.0.6)'
        required: true
jobs:
  release:
    runs-on: ubuntu-24.04
    env:
      BETA: ${{
          contains(github.event.inputs.grails_version, 'M') ||
          contains(github.event.inputs.grails_version, 'RC')
        }}
      SKIP_SNAPSHOT: ${{
          startsWith(github.event.inputs.grails_version, '3.3') ||
          startsWith(github.event.inputs.grails_version, '4.1') ||
          startsWith(github.event.inputs.grails_version, '5.3') ||
          startsWith(github.event.inputs.grails_version' '6.2') ||
          contains(github.event.inputs.grails_version, 'M') ||
          contains(github.event.inputs.grails_version, 'RC')
        }}
      GIT_USER_NAME: grails-build
      GIT_USER_EMAIL: grails-build@users.noreply.github.com
    steps:
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔀 Extract branch name"
        if: success() && github.event_name == 'workflow_dispatch'
        id: extract_branch
        run: echo "value=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: "🏷️ Create and Push Release Tag"
        uses: ./.github/actions/tag-and-release
        if: success() && github.event_name == 'workflow_dispatch'
        with:
          target_branch: ${{ steps.extract_branch.outputs.value }}
          grails_version: ${{ github.event.inputs.grails_version }}
      - name: "🎉 Create GitHub Release"
        if: success() && github.event_name == 'workflow_dispatch'
        id: create_release
        uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0 (Use commit sha as this is a 3rd party action)
        with:
          tag: v${{ github.event.inputs.grails_version }}
          name: ${{ github.event.inputs.grails_version }}
          prerelease: ${{ env.BETA }}
      - name: "🔨 Generate Documentation"
        env:
          TARGET_GRAILS_VERSION: ${{ github.event.inputs.grails_version }}
        run: >
          ./gradlew assemble
          -PgithubBranch=${{ steps.extract_branch.outputs.value }}
          --info --stacktrace
      - name: "📤 Upload Asset to the Github Release page"
        if: success() && github.event_name == 'workflow_dispatch'
        id: upload_artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@c15e0b65ce2ae1c8d52bfbc75d017d21e1da77d7 # v3.0.0 (Use commit sha as this is a 3rd party action)
        with:
          args: ./build/distributions/grails-docs-${{ github.event.inputs.grails_version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "📤 Publish to Github Pages"
        if: success()
        uses: grails/github-pages-deploy-action@f1bddf4d126e4375529c0f397b028eb5ac9a13e6 # 2024-12-22
        env:
          BRANCH: gh-pages
          COMMIT_EMAIL: ${{ env.GIT_USER_EMAIL }}
          COMMIT_NAME: ${{ env.GIT_USER_NAME }}
          FOLDER: build/docs
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          VERSION: ${{ github.event.inputs.grails_version }}
