# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Release - Create grails-core"
on:
  release:
    types: [published]
permissions: {}
env:
  # to prevent throttling of the github api, include the github token in an environment variable since the build will check for it
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    permissions:
      contents: write  #  to create release & upload wrapper
      issues: write  #  to modify milestones
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_version.outputs.value }}
      target_branch: ${{ steps.extract_branch.outputs.value }}
    steps:
      - name: "Output Agent IP" # in the event RAO blocks this agent, this can be used to debug it
        run: curl -s https://api.ipify.org
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "Ensure source files use common date"
        run: |
          find . -depth \( -type f -o -type d \) -exec touch -d "@${SOURCE_DATE_EPOCH}" {} +
      - name: '🔐 Set up GPG'
        run: |
          echo "${{ secrets.GRAILS_GPG_KEY }}" | gpg --batch --import
          gpg --list-keys
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '17.0.14' # this must be a specific version for reproducible builds
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "📝 Store the target branch"
        id: extract_branch
        run: |
          echo "Determining Target Branch"
          TARGET_BRANCH=`cat $GITHUB_EVENT_PATH | jq '.release.target_commitish' | sed -e 's/^"\(.*\)"$/\1/g'`
          echo $TARGET_BRANCH
          echo "value=${TARGET_BRANCH}" >> $GITHUB_OUTPUT
      - name: "📝 Store the current release version"
        id: release_version
        run: echo "value=${GITHUB_REF:11}" >> $GITHUB_OUTPUT
      - name: '⚙️ Run pre-release'
        uses: apache/grails-github-actions/pre-release@asf
        env:
          RELEASE_VERSION: ${{ steps.release_version.outputs.value }}
          RELEASE_SCRIPT_PATH: '.github/scripts/setReleasedGrailsVersion.sh'
      - name: "🧩 Run Assemble"
        id: assemble
        run: ./gradlew assemble
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
      - name: "🔏 Sign wrapper ZIP"
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          gpg --default-key "${GPG_KEY_ID}" --batch --yes --pinentry-mode loopback --armor --detach-sign grails-wrapper/build/distributions/apache-grails-wrapper-${{ steps.release_version.outputs.value }}-incubating-bin.zip
      - name: "📦 Create wrapper checksum"
        run: |
          cd grails-wrapper/build/distributions
          sha512sum apache-grails-wrapper-${{ steps.release_version.outputs.value }}-incubating-bin.zip > "apache-grails-wrapper-${{ steps.release_version.outputs.value }}-incubating-bin.zip.sha512"
      - name: "📤 Upload grails wrapper ZIP"
        uses: softprops/action-gh-release@v2
        with:
          files: |
            grails-wrapper/build/distributions/apache-grails-wrapper-${{ steps.release_version.outputs.value }}-incubating-bin.zip
            grails-wrapper/build/distributions/apache-grails-wrapper-${{ steps.release_version.outputs.value }}-incubating-bin.zip.sha512
            grails-wrapper/build/distributions/apache-grails-wrapper-${{ steps.release_version.outputs.value }}-incubating-bin.zip.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Staging Repository"
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-core:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew initializeSonatypeStagingRepository
      - name: "📤 Publish Gradle Plugins"
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-core:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew
          -x initializeSonatypeStagingRepository
          findSonatypeStagingRepository 
          publishToSonatype 
          aggregateChecksums
          aggregatePublishedArtifacts
      - name: "📤 Publish Grails-Core"
        id: publish
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-core:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        run: >
          ./gradlew
          -x initializeSonatypeStagingRepository
          findSonatypeStagingRepository 
          publishToSonatype 
          aggregateChecksums
          aggregatePublishedArtifacts
      - name: "📤 Close Staging Repository"
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
          NEXUS_PUBLISH_USERNAME: ${{ secrets.NEXUS_STAGE_DEPLOYER_USER }}
          NEXUS_PUBLISH_PASSWORD: ${{ secrets.NEXUS_STAGE_DEPLOYER_PW }}
          NEXUS_PUBLISH_URL: 'https://repository.apache.org/service/local/'
          NEXUS_PUBLISH_STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}
          NEXUS_PUBLISH_DESCRIPTION: 'grails-core:${{ steps.release_version.outputs.value }}'
          SIGNING_KEY: ${{ secrets.GPG_KEY_ID }}
        run: >
          ./gradlew
          -x initializeSonatypeStagingRepository
          findSonatypeStagingRepository 
          closeSonatypeStagingRepository
      - name: "🩹Combine checksums"
        run: |
          combined_file="build/CHECKSUMS.txt"
          cat build/grails-core-checksums.txt > "$combined_file"
          cat grails-gradle/build/grails-gradle-checksums.txt >> "$combined_file"
      - name: "Upload combined checksums"
        uses: softprops/action-gh-release@v2
        with:
          files: build/CHECKSUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "🩹Combine published artifacts"
        run: |
          combined_file="build/PUBLISHED_ARTIFACTS.txt"
          cat build/grails-core-artifacts.txt > "$combined_file"
          cat grails-gradle/build/grails-gradle-artifacts.txt >> "$combined_file"
      - name: "Upload combined published artifacts"
        uses: softprops/action-gh-release@v2
        with:
          files: build/PUBLISHED_ARTIFACTS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Generate Build Date file"
        run: echo "$SOURCE_DATE_EPOCH" >> build/BUILD_DATE.txt
      - name: "Upload Build Date file"
        uses: softprops/action-gh-release@v2
        with:
          files: build/BUILD_DATE.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    environment: release
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for gradle.properties revert
      issues: write # required for milestone closing
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: v${{ needs.publish.outputs.release_version }}
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "⚙️ Run post-release"
        uses: apache/grails-github-actions/post-release@asf
        env:
          RELEASE_SCRIPT_PATH: '.github/scripts/setSnapshotGrailsVersion.sh'
  docs:
    environment: docs
    name: "Publish Documentation"
    needs: publish
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.publish.outputs.release_version }}
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "📖 Generate Documentation"
        run: ./gradlew grails-doc:build -PgithubBranch=${{ needs.publish.outputs.target_branch }}
        env:
          GRAILS_PUBLISH_RELEASE: 'true'
      - name: "🚀 Publish to Github Pages"
        uses: apache/grails-github-actions/deploy-github-pages@asf
        env:
          GH_TOKEN: ${{ secrets.GRAILS_GHTOKEN }}
          TARGET_REPOSITORY: 'apache/grails-doc'
          GRADLE_PUBLISH_RELEASE: 'true'
          SOURCE_FOLDER: grails-doc/build/docs
          VERSION: ${{ needs.publish.outputs.release_version }}
