# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Release - Upload to dist.apache.org"
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v7.0.0-M4)'
        required: true
        type: string
env:
  SVN_USERNAME: ${{ secrets.SVC_DIST_GRAILS_USERNAME }}
  SVN_PASSWORD: ${{ secrets.SVC_DIST_GRAILS_PASSWORD }}
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: "Extract release version"
        id: release_version
        run: |
          version="${{ github.event.inputs.release_tag }}"
          echo "version=${version#v}" >> $GITHUB_OUTPUT
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
        with:
          repository: apache/grails-core
          ref: '7.0.x' # TODO: Temporary to minimize staging
          path: grails-core
      - name: "Setup SVN and Tools"
        run: sudo apt-get install -y subversion subversion-tools
      - name: "Ensure grails release folder exists"
        run: |
          set -e

          if svn ls https://dist.apache.org/repos/dist/release/grails --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive; then
            echo "Release Folder 'grails' already exists — skipping creation"
          else
            echo "Release Folder 'grails' does not exist, creating"
            svnmucc --non-interactive \
              --username "$SVN_USERNAME" \
              --password "$SVN_PASSWORD" \
              mkdir https://dist.apache.org/repos/dist/release/grails \
              -m "Create 'grails' release folder"
          fi
      - name: "Ensure grails dev folder exists"
        run: |
          set -e

          if svn ls https://dist.apache.org/repos/dist/dev/grails --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --non-interactive; then
            echo "Dev Folder 'grails' already exists — skipping creation"
          else
            echo "Dev Folder 'grails' does not exist, creating"
            svnmucc --non-interactive \
              --username "$SVN_USERNAME" \
              --password "$SVN_PASSWORD" \
              mkdir https://dist.apache.org/repos/dist/dev/grails \
              -m "Create 'grails' dev folder"
          fi
#      - name: "Checkout release repo"
#        run: |
#          svn checkout --non-interactive --username "$SVN_USERNAME" --password "$SVN_PASSWORD" https://dist.apache.org/repos/dist/release/grails release-repo
#      - name: "Update KEYS file"
#        run: |
#          if ! cmp -s grails-core/KEYS release-repo/KEYS; then
#            echo "KEYS file differs — committing update"
#            cp grails-core/KEYS release-repo/
#            cd release-repo
#            svn add KEYS --force
#            svn commit -m "Update grails KEYS file" --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
#          else
#            echo "KEYS file unchanged — skipping commit"
#          fi
      - name: "Checkout dev repo"
        run: |
          svn checkout --non-interactive --username "$SVN_USERNAME" --password "$SVN_PASSWORD" https://dist.apache.org/repos/dist/dev/grails dev-repo
      - name: "Remove existing dev version"
        run: |
          VERSION="${{ steps.release_version.outputs.version }}"
          cd dev-repo
          if [ -d "$VERSION" ]; then
            svn delete "$VERSION"
            svn commit -m "Remove grails dev version $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
          else
            echo "No existing dev version $VERSION to remove"
          fi
      - name: "Upload source distribution"
        run: |
          TAG=${{ github.event.inputs.release_tag }}
          VERSION=${{ steps.release_version.outputs.version }}
          cd dev-repo
          mkdir -p $VERSION/source          
          cd $VERSION/source
          curl -LO https://github.com/apache/grails-core/releases/download/$TAG/apache-grails-$VERSION-incubating-src.zip
          curl -LO https://github.com/apache/grails-core/releases/download/$TAG/apache-grails-$VERSION-incubating-src.zip.sha512
          curl -LO https://github.com/apache/grails-core/releases/download/$TAG/apache-grails-$VERSION-incubating-src.zip.asc
          echo "Adding the following files:"
          ls -l
          cd ../..
          svn add $VERSION --force
          svn commit -m "Upload grails source files for $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
      - name: "Upload grails binary distribution"
        run: |
          TAG=${{ github.event.inputs.release_tag }}
          VERSION=${{ steps.release_version.outputs.version }}
          cd dev-repo
          mkdir -p $VERSION/distribution
          cd $VERSION/distribution
          curl -LO https://github.com/apache/grails-forge/releases/download/$TAG/apache-grails-$VERSION-incubating-bin.zip
          curl -LO https://github.com/apache/grails-forge/releases/download/$TAG/apache-grails-$VERSION-incubating-bin.zip.sha512
          curl -LO https://github.com/apache/grails-forge/releases/download/$TAG/apache-grails-$VERSION-incubating-bin.zip.asc
          echo "Adding the following files:"
          ls -l
          cd ../..
          svn add $VERSION --force
          svn commit -m "Upload grails binary distribution for $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD"
      - name: "Upload grails wrapper binary distribution"
        run: |
          TAG=${{ github.event.inputs.release_tag }}
          VERSION=${{ steps.release_version.outputs.version }}
          cd dev-repo/$VERSION/distribution
          curl -LO https://github.com/apache/grails-core/releases/download/$TAG/apache-grails-wrapper-$VERSION-incubating-bin.zip
          curl -LO https://github.com/apache/grails-core/releases/download/$TAG/apache-grails-wrapper-$VERSION-incubating-bin.zip.sha512
          curl -LO https://github.com/apache/grails-core/releases/download/$TAG/apache-grails-wrapper-$VERSION-incubating-bin.zip.asc
          echo "Adding the following files:"
          ls -l
          cd ../..
          svn add $VERSION --force
          svn commit -m "Upload grails wrapper binary distribution for $VERSION" --username "$SVN_USERNAME" --password "$SVN_PASSWORD"