////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

== Querying
RxGORM supports all the typical ways of querying that you are used to with GORM including:

* https://gorm.grails.org/latest/hibernate5/manual/index.html#finders[Dynamic finders]
* https://gorm.grails.org/latest/hibernate5/manual/index.html#whereQueries[Where queries]
* https://gorm.grails.org/latest/hibernate5/manual/index.html#detachedCriteria[Detached Criteria]
* https://gorm.grails.org/latest/hibernate5/manual/index.html#criteria[Criteria queries]

The major difference is that all query operations return an `Observable`. In this section we will go through the various ways you can query for GORM objects.

include::basicQuerying.adoc[]

include::whereQueries.adoc[]

include::dynamicFinders.adoc[]
