////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

If you set the configuration property `logging.config`, you can instruct `Logback` to use an external configuration file.

[source,yaml]
.grails-app/conf/application.yml
----
logging:
    config: /Users/me/config/logback-spring.xml
----

Alternatively, you can supply the configuration file location with a system property:

`$ ./gradlew -Dlogging.config=/Users/me/config/logback-spring.xml bootRun`

Or, you could use an environment variable:

[source, bash]
----
$ export LOGGING_CONFIG=/Users/me/config/logback-spring.xml
$ ./gradlew bootRun
----


