////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

When Grails logs a stacktrace, the log message may include the names and values of all of the request parameters for the current request.
To mask out the values of secure request parameters, specify the parameter names in the `grails.exceptionresolver.params.exclude` config property:

[source, yaml]
.grails-app/conf/application.yml
----
grails:
    exceptionresolver:
        params:
            exclude:
                - password
                - creditCard
----

Request parameter logging may be turned off altogether by setting the `grails.exceptionresolver.logRequestParameters`
config property to false. The default value is true when the application is running in DEVELOPMENT mode and false for all other
environments.

[source, yaml]
.grails-app/conf/application.yml
----
grails:
    exceptionresolver:
        logRequestParameters: false
----
